version: '3'

services: 
    ssr:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - ./node_modules
            - ./:/usr/app
        ports: 
            - "8080:3000"
